---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен быть доступен на различных устройствах
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Сайт должен открываться на языке, соответствующим локализации пользователя
  - Цена товара должна быть в валюте пользователя, соответственно его локализации
  - Кнопка добавления товара в корзину должна выделяться (быть яркой)
  - Смена языка должна быть вверху страницы для легкого обнаружения
  - Цена товара со скидкой должна быть выделена красным цветом
