---
functional:
  - Требование 3
  - Требование 4
  - Требование 5
  - Требование 6
  - Требование 8
  - Требование 9
  - Требование 10
non-functional:
  - Требование 1
  - Требование 2
  - Требование 7
implicit:
  - Сайт должен открываться на языке, соответствуещем локализации пользователя
  - Цена товара должна быть в валюте пользователя, соответственно его локализации
  - Кнопка добавления товара в корзину должна выделяться (быть яркой)
  - Смена языка должна быть вверху страницы для легкого обнаружения
  - Цена товара со скидкой должна быть выделена красным цветом
